#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export EDITOR=nvim
export TERMINAL=alacritty

alias ls='ls --color=auto'
alias grep='grep --color=auto'

## Prompt
PS1=' \[\033[01;32m\]\u\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] > '
