vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set number")
vim.cmd("set cursorline")
vim.cmd("hi CursorLine term=bold cterm=bold ctermbg=236")
vim.cmd("hi CursorLineNr term=bold cterm=bold ctermbg=236")
