## Color fixes
set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"

## Change Prefix
unbind C-b
set -g prefix C-s
bind C-Space send-prefix 

## Focusing Panes
bind-key -r h select-pane -L
bind-key -r j select-pane -D
bind-key -r k select-pane -U
bind-key -r l select-pane -R

## Splits
bind-key C-v split-window -h
bind-key C-h split-window -v
