## Color fixes
set -g default-terminal "xterm-256color"
set-option -sa terminal-features ',xterm-256color:RGB'
set-option -g default-terminal "tmux-256color"
set-option -ga terminal-features ",xterm-256color:usstyle"


## To relaod config file on the fly
unbind r
bind r source-file ~/.config/tmux/tmux.conf

## Rebind Leader combination
set -g prefix C-f

## Window navigation vim style
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

## Creating splits
bind-key | split-window -h
