# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# Custom environment variables
if [ -f  "$HOME/.customenv" ]; then
    . "$HOME/.customenv";
fi

# Startup
 if [ -f "$HOME/.devicespecific.sh" ]; then
     sh "$HOME/.devicespecific.sh"
 fi
