#!/bin/sh

# Remove old file config file
if [ -f "$HOME/.config/niri/config.kdl" ]; then
        rm "$HOME/.config/niri/config.kdl"
fi


# rewrite everyting into the config file
cat $HOME/.config/niri/*.kdl > rm "$HOME/.config/niri/config.kdl"
