
set tabstop=4
set shiftwidth=4
set expandtab
set softtabstop=4

syntax on

set number
" setting cursor variables

" Setting leader to SPACE
let mapleader = " "

" Set cursor shape in normal mode to a bar
let &t_SI = "\e[5 q"   " cursor in insert mode
let &t_EI = "\e[2 q"   " cursor in normal mode
let &t_SR = "\e[3 q"   " cursor in replace mode
let &t_ti .= "\e[2 q"  " cursor when vim starts
let &t_te .= "\e[3 q"  " cursor when vim exits 

" enable cursor line
set cursorline

" hi CursorLine cterm=NONE guibg=#ffffff 
hi CursorLine term=bold cterm=bold ctermbg=236

" set color scheme
colorscheme habamax

" Split down and right by default
set splitbelow
set splitright

" for Cursor
set ttimeout 
set ttimeoutlen=1
set ttyfast

" indent when hitting enter
set smartindent

" Set terminal size to 20x200
set termwinsize=20x200

" Keybindings
"" F12 to launch terminal
nmap <F12>  :terminal<CR>

"" Unfocus terminal 
tnoremap <Esc><Esc> <C-\><C-n> 

"" Navigate between splits
nmap <c-k> :wincmd k<CR>
nmap <c-j> :wincmd j<CR>
nmap <c-h> :wincmd h<CR>
nmap <c-l> :wincmd l<CR>

"" Start Explore on the left 
nmap <leader>ff :Explore <CR>

"" Buffer Navigation
nmap <leader>nn :bnext <CR>
nmap <leader>NN :bprevious <CR>
nmap <leader>qq :bdelete<CR>
nmap <leader>bb :buffers<CR>



" Enable Status line
set laststatus=2

" source user-specific config
if !empty(glob("$HOME/.vim/customized/customized"))
    source $HOME/.vim/customized/customized
endif

" Enable OS-Clipboard
" set clipboard=unnamedplus
