
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# env Exports
export WLR_NO_HARDWARE_CURSORS=1

## NNN  Configuration
export NNN_PLUG='D:mkdir.sh;x:extract.sh;d:trash.sh'

## Set EDITOR
(command -v nvim > /dev/null) && export EDITOR=nvim || export EDITOR=vim

# Startup
 if [ -f "$HOME/.devicespecific.sh" ]; then
     sh "$HOME/.devicespecific.sh"
 fi
