#!/bin/sh

OUTPUTVGA="$(wlr-randr | grep -o VGA | sed -n 1p)"
OUTPUTHDMI="$(wlr-randr | grep -o HDMI | sed -n 1p)"
OUTPUTDVI="$(wlr-randr | grep -o DVI | sed -n 1p)"
OUTPUTDP="$(wlr-randr | grep -o DP | sed -n 1p)"

if [ -n "$OUTPUTVGA" ] || [ -n "$OUTPUTHDMI" ] || [ -n "$OUTPUTDVI" ] || [ -n "$OUTPUTDP" ]
then
        wlr-randr --output LVDS-2 --off
else
        wlr-randr --output LVDS-2 --on
fi

