#!/bin/bash

MENTRIES="$(echo " Shutdown
 Reboot
 Logout
 Suspend
 Hibernate
 Lock" | rofi -dmenu -config ~/.config/rofi/config2.rasi)"

MOPTIONS="$(echo $MENTRIES | awk '{print$2}' |tr '[:upper:]' '[:lower:]')"
echo $MOPTIONS

if [[ -n "$MOPTIONS" ]]
then

if [[ "$MOPTIONS" == logout ]]
then 
        swaymsg exit
else
        if [[ "$MOPTIONS" == lock ]]
        then
                swaylock
        else
systemctl $MOPTIONS
fi
fi
fi
