" Setting tabbing
set tabstop=4
set shiftwidth=4
set expandtab
set softtabstop=4

" Syntax highlighting
syntax on

" Show line numbers
set number

" setting cursor variables
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_SR = "\<Esc>]50;CursorShape=2\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"
set ttimeout
set ttimeoutlen=1
set ttyfast

" autoindent on newline
set smartindent

" source user-specific file if it exists
if filereadable("$HOME/.config/vim/devicespecific")
    source $HOME/.config/vim/devicespecific
endif
