
set tabstop=8
set shiftwidth=4
set noexpandtab
set softtabstop=4

syntax on

set number
" setting cursor variables

" Set cursor shape in normal mode to a bar
let &t_SI = "\e[2 q"   " cursor in insert mode
let &t_EI = "\e[2 q"   " cursor in normal mode
let &t_SR = "\e[3 q"   " cursor in replace mode
let &t_ti .= "\e[2 q"  " cursor when vim starts
let &t_te .= "\e[3 q"  " cursor when vim exits 


set ttimeout 
set ttimeoutlen=1
set ttyfast
set smartindent

" source user-specific config

if !empty(glob("$HOME/.config/vim/devicespecific"))
    source $HOME/.config/vim/devicespecific
endif
